---
# roles/common/tasks/fedora.yml

- include: chrome.yml

- name: Install yum packages
  yum: name={{ item }} state=present
  with_items: yum_packages
  tags: pkg

- name: Update and upgrade system
  yum: name=* state=latest
  tags: update
  ignore_errors: yes

- name: Install gem packages
  gem: name={{ item }} state=latest
  with_items: gem_packages

