---
# gnome variables

gsettings:
  key: org.gnome.desktop.interface.icon-theme
    value: Faenza-Darker
  key: org.gnome.desktop.interface.clock-show-date
    value: true
  keys: org.gnome.desktop.wm.preferences.mouse-button-modifier
    value: '<alt>'
