---
# roles/common/tasks/main.yml
# requires gsettings module

- name: Change dconf settings
  gsetting: "user={{ ansible_ssh_user }}
    key={{ item.value.key }}
    value={{ item.value.value }}"
  with_dict: gsettings
  ignore_errors: true
