---
# roles/common/tasks/main.yml
# requires gsettings module

- name: Change dconf settings
  dconf: key={{ item.value.key }}
    value={{ item.value.value }}
  with_dict: "{{ gsettings }}"
  ignore_errors: true
