---
# roles/common/tasks/ubuntu.yml

- name: Update and upgrade system
  apt: upgrade=yes update_cache=yes
  tags: update
  ignore_errors: yes

- name: Add repos and ppas
  apt_repository: repo={{ item }}
  with_items: ppas
  ignore_errors: yes

- name: Install apt packages
  apt: name={{ item }} state=installed force=yes
  with_items: apt_packages

- name: Check hard drive temps
  command: hddtemp -S 60 /dev/{{ item }}
  with_items: ansible_devices.keys()
  
- name: Install Chrome
  include: chrome.yml
  when: ansible_distribution == 'ubuntu'_

- name: Install Docker
  include: docker.yml
  when: ansible_distribution == 'ubuntu'_
