---
yum_packages:
# rpm fusion repos
  - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
  - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
  - ack
  - ansible
  - autokey-gtk
  - curl
  - dconf-editor
  - git
  - glances
  - gnome-tweak-tool
  - gstreamer1-libav
  - gstreamer1-plugins-bad-freeworld 
  - gstreamer1-plugins-good 
  - gstreamer-plugins-bad-free 
  - gstreamer-plugin-crystalhd 
  - gstreamer1-vaapi
  - hddtemp
  - htop
  - httpie
  - iotop
  - jq
  - mosh
  - petit
  - ncdu
  - openssh-server
  - pm-utils
  - pv
  - glances
  - python-setuptools
  - remmina
  - remmina-plugins-gnome
  - rootsh
  - rubygems
  - shutter
  - system-storage-manager
  - the_silver_searcher
  - tmux
  - tmuxinator
  - tsocks
  - tree
  - vlc
  - weechat
  - xclip
  - zsh
services:
  - name: sshd
    status: running
    enabled: True
