---
yum_packages:
# rpm fusion repos
  - ack
  - ansible
  - autokey-gtk
  - curl
  - dconf-editor
  - git
  - git-extras
  - glances
  - golang
  - gnome-tweak-tool
  - gstreamer-plugins-bad-free 
  - gstreamer-plugin-crystalhd 
  - hddtemp
  - htop
  - httpie
  - iotop
  - jq
  - mosh
  - nautilus-open-terminal
  - ncdu
  - openssh-server
  - petit
  - pv
  - python-setuptools
  - remmina
  - remmina-plugins-gnome
  - rootsh
  - rubygems
  - shutter
  - system-storage-manager
  - the_silver_searcher
  - tmux
  - tmuxinator
  - tsocks
  - tree
  - weechat
  - xclip
  - zsh
rpmfusion_packages:
  - gstreamer1-libav
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-plugins-good
  - gstreamer1-vaapi
  - vlc
services:
  - name: sshd
    status: running
    enabled: True
go_env:
  GOPATH: "/home/{{ ansible_env.USERNAME }}"
go_binaries:
  - github.com/moul/advanced-ssh-config/cmd/assh
