---
yum_packages:
  - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
  - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
  - ansible
  - autokey-gtk
  - curl
  - dconf-editor
  - git
  - glances
  - gnome-tweak-tool
  - gstreamer1-libav
  - gstreamer1-plugins-bad-freeworld 
  - gstreamer1-plugins-good 
  - gstreamer-plugins-bad-free 
  - gstreamer-plugin-crystalhd 
  - gstreamer1-vaapi
  - hddtemp
  - htop
  - iotop
  - ncdu
  - openssh-server
  - pv
  - glances
  - python-setuptools
  - remmina
  - remmina-plugins-gnome
  - rubygems
  - sshfs
  - shutter
  - tmux
  - tree
  - vim
  - vlc
  - weechat
  - xclip
  - zsh
