---
# roles/common/tasks/main.yml

- name: Update and upgrade system
  apt: upgrade=dist update_cache=yes

- name: Add repos and ppas
  apt_repository: repo={{ item }}
  with_items: ppas

- name: add virtualbox repo and key
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
- apt_key: url=http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc state=present

- name: Install common packages
  apt: name={{ item }} state=installed
  with_items: apt_packages

- name: Install pip (if needed)
  shell: easy_install pip
  ignore_errors: yes

- name: Install common packages
  pip: name={{ item }} state=present
  with_items: pip_packages

- name: Clone my dotfiles
  git: repo={{ dotfiles.repo }} dest=~/.dotfiles
    recursive=yes accept_hostkey=yes

- name: Install sysdig
  include: sysdig.yml

- name: Install Chrome
  include: chrome.yml
