---
# roles/common/tasks/main.yml

- name: Update and upgrade system
  apt: upgrade=yes update_cache=yes
  tags: update
  ignore_errors: yes

- name: Add repos and ppas
  apt_repository: repo={{ item }}
  with_items: ppas
  ignore_errors: yes

- name: Install apt packages
  apt: name={{ item }} state=installed force=yes
  with_items: apt_packages

- name: Install pip (if needed)
  easy_install: name=pip

- name: Install pip packages
  pip: name={{ item }} state=latest
  with_items: pip_packages
  
- name: Install gem packages
  gem: name={{ item }} state=latest
  with_items: gem_packages

- name: Check hard drive temps
  command: hddtemp -S 60 /dev/{{ item }}
  with_items: ansible_devices.keys()

- name: Clone my dotfiles
  git: repo={{ dotfiles.repo }} dest=/home/{{ ansible_user_id }}/.dotfiles
    recursive=yes accept_hostkey=yes

- name: Change user shell to zsh
  shell: chsh -s /usr/bin/zsh {{ ansible_user_id }}

- name: Create zprezto symlinks
  shell: /home/{{ ansible_user_id }}/.dotfiles/init/zprezto-install.sh
    creates=/home/{{ ansible_user_id }}/.dotfiles/src/.zshrc

- name: Create dotfiles symlinks
  shell: /home/{{ ansible_user_id }}/.dotfiles/init/dotfiles-install.sh
    creates=/home/{{ ansible_user_id }}/.zshenv
  
- name: Install Chrome
  include: chrome.yml

- name: Install Docker
  include: docker.yml
