---
# roles/common/tasks/main.yml

- name: Clone my dotfiles
  git: repo={{ dotfiles.repo }} dest=/home/{{ ansible_env.SUDO_USER }}/.dotfiles
    recursive=yes accept_hostkey=yes update=yes track_submodules=yes
  sudo: no

- name: Set dotfiles ownership
  file: path=/home/{{ ansible_env.SUDO_USER }}/.dotfiles recurse=yes
    owner={{ ansible_env.SUDO_USER }} group={{ ansible_env.SUDO_USER }}

- name: Create zprezto symlinks
  shell: /home/{{ ansible_env.SUDO_USER }}/.dotfiles/init/zprezto-install.sh
    creates=/home/{{ ansible_env.SUDO_USER }}/.dotfiles/src/.zshrc
  sudo: no

- name: Create dotfiles symlinks
  shell: /home/{{ ansible_env.SUDO_USER }}/.dotfiles/init/dotfiles-install.sh
    creates=/home/{{ ansible_env.SUDO_USER }}/.zshenv
  sudo: no

- name: Install pip (if needed)
  easy_install: name=pip

- name: Install pip packages
  pip: name={{ item }} state=latest
  with_items: pip_packages

