---
# roles/common/tasks/main.yml

- name: Update and upgrade system
  apt: upgrade=yes update_cache=yes
  ignore_errors: yes

- name: Add repos and ppas
  apt_repository: repo={{ item }}
  with_items: ppas
  ignore_errors: yes

- name: add virtualbox repo and key
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
  when: ansible_distribution_version == "14.04"
- apt_key: url=http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc state=present
  when: ansible_distribution_version == "14.04"

- name: Install apt packages
  apt: name={{ item }} state=installed force=yes
  with_items: apt_packages

- name: Install pip (if needed)
  shell: easy_install pip
  ignore_errors: yes

- name: Install pip packages
  pip: name={{ item }} state=latest
  with_items: pip_packages
  
- name: Install gem packages
  gem: name={{ item }} state=latest
  with_items: gem_packages

- name: Check hard drive temps
  command: hddtemp -S 60 /dev/{{ item }}
  with_items: ansible_devices.keys()

- name: Clone my dotfiles
  git: repo={{ dotfiles.repo }} dest=~/.dotfiles
    recursive=yes accept_hostkey=yes

- name: Install sysdig
  include: sysdig.yml
  when: ansible_distribution_version == "14.04"

- name: Install Chrome
  include: chrome.yml
