---
# roles/common/tasks/main.yml

- name: Update and upgrade system
  apt: upgrade=dist update_cache=yes

- name: Add repos and ppas
  apt_repository: repo={{ item }}
  with_items: ppas

- name: Install common packages
  apt: name={{ item }} state=installed
  with_items: apt-packages

- name: Install common packages
  pip: name={{ item }} state=present
  with_items: pip-packages

- name: Install sysdig
  include: sysdig.yml

- name: Install Chrome
  include: chrome.yml
