---
apt_packages:
  - gdebi
  - openssh-server
  - vim
  - zsh
  - git
  - build-essential
  - tmux
  - vlc
  - htop
  - iotop
  - irssi
  - ncdu
  - glances
  - dkms # virtualbox req
  - virtualbox
  - handbrake
  - python-setuptools
  - autokey-gtk
  - remmina
  - remmina-plugin-gnome
  - ansible
  - xclip
  - hddtemp
  - weechat
  - curl

pip_packages:
  - beets

gem_packages:
  - tmuxinator

apt_file: "/etc/apt/sources.list.d/google-chrome.list"

dotfiles: {
  "repo": "https://github.com/rothgar/dotfiles.git",
  "host": "www.github.com",
}
